export const jsdocRules = {
  'jsdoc/check-access': 'warn',
  'jsdoc/check-alignment': 'warn',
  'jsdoc/check-indentation': ['warn', { excludeTags: ['param', 'returns', 'example'] }],
  'jsdoc/check-line-alignment': 'warn',
  'jsdoc/check-param-names': 'warn',
  'jsdoc/check-property-names': 'warn',
  'jsdoc/check-syntax': 'warn',
  'jsdoc/check-tag-names': 'warn',
  'jsdoc/check-types': 'warn',
  'jsdoc/check-values': 'warn',
  'jsdoc/empty-tags': 'warn',
  'jsdoc/implements-on-classes': 'warn',
  'jsdoc/informative-docs': ['warn', { excludedTags: ['default'] }],
  'jsdoc/match-description': ['warn', { matchDescription: '^\n?([*A-Z`\\d_][\\s\\S]*([.?!`]|\\*\\w+\\*{1,3})\\s*)?$' }],
  'jsdoc/multiline-blocks': ['error', { noSingleLineBlocks: true, singleLineTags: ['*'] }],
  'jsdoc/no-bad-blocks': 'warn',
  'jsdoc/no-blank-block-descriptions': 'warn',
  'jsdoc/no-defaults': 'warn',
  'jsdoc/no-multi-asterisks': ['warn', { allowWhitespace: true }],
  'jsdoc/require-asterisk-prefix': 'warn',
  'jsdoc/require-hyphen-before-param-description': 'warn',
  'jsdoc/require-param': 'warn',
  'jsdoc/require-param-name': 'warn',
  'jsdoc/require-param-type': 'warn',
  'jsdoc/require-property': 'warn',
  'jsdoc/require-property-name': 'warn',
  'jsdoc/require-property-type': 'warn',
  'jsdoc/require-returns-check': 'warn',
  'jsdoc/require-returns-type': 'warn',
  'jsdoc/require-throws': 'warn',
  'jsdoc/require-yields': 'warn',
  'jsdoc/require-yields-check': 'warn',
  'jsdoc/sort-tags': 'warn',
  'jsdoc/tag-lines': ['warn', 'always', { count: 0, applyToEndTag: false }],
  'jsdoc/valid-types': 'warn',
  // 'jsdoc/no-undefined-types': 'warn',
};
